### ISSUE TITLE
Errors in com.subgraph.vega.http.conditions

### ISSUE THREAD

**Issue by consiliens** [subgraph/Vega#1]
I followed https://support.subgraph.com/trac/wiki/BuildingVega using Eclipse Indigo.  There are many errors in com.subgraph.vega.http.conditions.  Is this a known problem?

**Comment by subgraph** [comment]
Hi consiliens,

You can just delete that plugin (com.subgraph.vega.http.conditions) entirely from your Eclipse workspace.  We moved the condition framework code into the model plugin a few months ago and forgot to delete the old code from the git repository.

**Comment by consiliens** [comment]
Thanks for the response.
