### ISSUE TITLE
Newest build?

### ISSUE THREAD

**Issue by giveen** [subgraph/Vega#117]
The current version I downloaded from the subraph website is
Version: 1.0
Build id: devel-130

I'm curious is that the same one as that is currently being compiled on 
https://github.com/dma/Vega

Also, I've never compiled a java file before and I'm not familiar with build.xml files, could you put in your readme.md a compile guide?

**Comment by dma** [comment]
Hi giveen. Correct, the builds available for download are are built from the dev branch of my repo. Need to merge it back into subgraph/Vega, just haven't done that yet for a number of reasons.

As for your question about building Vega, there are instructions on our website:

https://subgraph.com/vega/documentation/Building-Vega/index.en.html

**Comment by giveen** [comment]
Thank you, that exactly what I needed.
