### ISSUE TITLE
Missing Java

### ISSUE THREAD

**Issue by giveen** [subgraph/Vega#119]
![java](https://cloud.githubusercontent.com/assets/1180939/6418397/0787a38e-be72-11e4-922b-d28d07a8963c.PNG)

I've reinstalled my Java, still not being detected. The folder it is asking for is not present in that directory. I manually copied it over, and it wont start with zero errors.

**Comment by dma** [comment]
Did you install the 32-bit version of Java or the 64-bit? Because Vega here is looking for the 32-bit JVM, which is why the path has (x86) in it. If you are sure you have the right version of Java installed, you can manually specify the path to the JVM in the Vega.ini file which is in the Vega application directory. Just add a parameter -vm path\to\javaw.exe.

Let me know if this helps.

**Comment by giveen** [comment]
Maybe thats why. I am using the x64. Let me try the x86 first.

**Comment by giveen** [comment]
Installed x86, not working. Same errors

Added 
-vm "C:\Program Files (x86)\Java\jre1.8.0_31\bin\javaw.exe"

to the vega.ini, same error.
What is weird is that Vega was working just fine for quite sometime.

Switched Java 7, still same issue
C:\Program Files (x86)\Java\jre7

**Comment by dma** [comment]
You're saying Vega used to work, but suddenly doesn't and now this happens? That is extremely weird. Can you un-install Vega and start over? I see you now have Java 7 x86 installed in the correct place. Following the uninstall of Vega, can you install the Vega 32-bit version and tell me if that works?

**Comment by giveen** [comment]
Sure, one moment. I did do an uninstall/install several times.....

Same error with 32bit

**Comment by giveen** [comment]
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\Jeremy\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=DALEK
ComSpec=C:\Windows\system32\cmd.exe
FP_NO_HOST_CHECK=NO
GPU_MAX_ALLOC_PERCENT=100
GPU_MAX_HEAP_SIZE=100
GPU_USE_SYNC_OBJECTS=1
HOMEDRIVE=C:
HOMEPATH=\Users\Jeremy
LOCALAPPDATA=C:\Users\Jeremy\AppData\Local
LOGONSERVER=\DALEK
NUMBER_OF_PROCESSORS=8
OS=Windows_NT
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD
PROCESSOR_LEVEL=21
PROCESSOR_REVISION=0200
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC=C:\Users\Public
pythonexe=C:\Python34\
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\Jeremy\AppData\Local\Temp
TMP=C:\Users\Jeremy\AppData\Local\Temp
USERDOMAIN=DALEK
USERNAME=Jeremy
USERPROFILE=C:\Users\Jeremy
windir=C:\Windows
windows_tracing_flags=3
windows_tracing_logfile=C:\BVTBin\Tests\installpackage\csilogfile.log

Do you think I need to add it into my system variables? I've never had to do that before.

**Comment by dma** [comment]
That change to the Vega.ini file you made is gone, right? It should have been overwritten during the reinstall. Try logging out and logging back in. Also try to run the Java executable, see if it works (print the version..). If it works, put it explicitly into your path - though as you say it shouldn't be necessary to do this.

**Comment by giveen** [comment]
Okay, lol, I guess we can close this.
I logged out and logged back in, still didnt fix it.

Reboot and it worked, which is weird, but I guess I feel like a moron. I wonder if I install the x64, if it will work after a reboot. Also, my java version is listing at 8, but its running. But because its not 7, I wonder if that is why I'm getting the script errors I had submitted. Kinda worried about installing and breaking what is now fixed.

I guess this can be closed now.

**Comment by dma** [comment]
It works. Great. The script error you saw is almost certainly unrelated to the version of Java you are running. It looks to me like a bug in Vega scanner core, and I think I've seen it before. Vega Javascript modules shouldn't be triggering Java NPEs.

**Comment by giveen** [comment]
Just to close this out completely. It ended up being a PATH issue.

**Comment by abduljalilmemon** [comment]
can u help me i am getting same problem

**Comment by abduljalilmemon** [comment]
-vmargs 
-Xms256m  
-Xmx2048m 
-XX:PermSize=128m 
-XX:MaxPermSize=256m 





-vm "C:\Program Files (x86)\Java\jre1.8.0_221\bin\javaw.exe"
