### ISSUE TITLE
Derivated work of xml/alerts

### ISSUE THREAD

**Issue by andresriancho** [subgraph/Vega#120]
https://github.com/subgraph/Vega/tree/develop/xml/alerts is something I could re-use and extend for my w3af project, but the licenses (http://www.eclipse.org/legal/epl-v10.html vs GPLv2) are incompatible.

Would you guys consider re-licensing the xml files so I can use/extend them?

**Comment by dma** [comment]
Hey Andres,

Sure, we can probably do that.

**Comment by andresriancho** [comment]
Problem already fixed in another way: https://github.com/vulndb/data/
