### ISSUE TITLE
Display not initialized properly after boot when using HVM in Qubes r3

### ISSUE THREAD

**Issue by n0sn3b** [subgraph/Vega#127]
When using SGOS ISO Alpha release from 02032016 and installing it as an HVM in Qubes R3, the screen is not initialized properly after boot up and is unusable.

That's when booting with the GRSEC kernel.

The older kernel (non GRSEC) seem to have the same issue initially but after a few seconds, it looks like the screen is initialized properly and becomes operational

There is no issues with the live version running as an HVM in Qubes and no issues with running the graphical installer. The issue is only when booting the freshly installed version of SGOS as an HVM.

non GRSEC old kernel:
user@subgraph:~$ lsmod
Module                  Size  Used by
fuse                   94208  3
nfnetlink_queue        20480  1
nfnetlink              16384  2 nfnetlink_queue
xt_REDIRECT            16384  3
nf_nat_redirect        16384  1 xt_REDIRECT
iptable_nat            16384  1
nf_nat_ipv4            16384  1 iptable_nat
nf_nat                 24576  2 nf_nat_redirect,nf_nat_ipv4
ipt_REJECT             16384  4
nf_reject_ipv4         16384  1 ipt_REJECT
xt_tcpudp              16384  6
xt_owner               16384  2
xt_multiport           16384  1
xt_mark                16384  2
iptable_filter         16384  1
nf_conntrack_ipv4      20480  4
nf_defrag_ipv4         16384  1 nf_conntrack_ipv4
xt_NFQUEUE             16384  2
xt_conntrack           16384  3
nf_conntrack          118784  4
nf_nat,nf_nat_ipv4,xt_conntrack,nf_conntrack_ipv4
iptable_mangle         16384  1
ip_tables              28672  3 iptable_filter,iptable_mangle,iptable_nat
ebtable_filter         16384  1
ebtables               36864  1 ebtable_filter
x_tables               36864  12
xt_mark,ip_tables,xt_tcpudp,xt_NFQUEUE,xt_owner,xt_conntrack,xt_multiport,iptable_filter,ebtables,ipt_REJECT,xt_REDIRECT,iptable_mangle
ppdev                  20480  0
bochs_drm              24576  3
ttm                    94208  1 bochs_drm
drm_kms_helper        131072  1 bochs_drm
drm                   348160  6 ttm,bochs_drm,drm_kms_helper
i2c_piix4              24576  0
psmouse               126976  0
serio_raw              16384  0
pcspkr                 16384  0
parport_pc             28672  0
8250_fintek            16384  0
parport                49152  2 ppdev,parport_pc
acpi_cpufreq           20480  0
processor              36864  1 acpi_cpufreq
button                 16384  0
evdev                  20480  7
joydev                 20480  0
hid_generic            16384  0
usbhid                 49152  0
hid                   118784  2 hid_generic,usbhid
autofs4                40960  2
ext4                  577536  2
crc16                  16384  1 ext4
mbcache                20480  1 ext4
jbd2                  106496  1 ext4
crct10dif_pclmul       16384  0
crc32_pclmul           16384  0
crc32c_intel           24576  0
ata_generic            16384  0
jitterentropy_rng      16384  0
sha256_ssse3           28672  1
sha256_generic         24576  1 sha256_ssse3
hmac                   16384  1
drbg                   24576  1
ansi_cprng             16384  0
xen_netfront           28672  0
xen_blkfront           36864  5
aesni_intel           167936  0
aes_x86_64             20480  1 aesni_intel
lrw                    16384  1 aesni_intel
gf128mul               16384  1 lrw
glue_helper            16384  1 aesni_intel
ablk_helper            16384  1 aesni_intel
cryptd                 20480  2 aesni_intel,ablk_helper
uhci_hcd               45056  0
ehci_hcd               77824  0
ata_piix               36864  0
libata                233472  2 ata_generic,ata_piix
usbcore               233472  3 uhci_hcd,ehci_hcd,usbhid
usb_common             16384  1 usbcore
scsi_mod              229376  1 libata
floppy                 69632  0

**Comment by dma** [comment]
Wrong repo. Please post this to the Subgraph OS issues repository: https://github.com/subgraph/subgraph_metaproxy
