### ISSUE TITLE
Vega is great. Did its development stop?

### ISSUE THREAD

**Issue by JerryLiao26** [subgraph/Vega#132]
Vega is quite a beautifully-designed and light-weighted web scanner and I like it a lot. But I noticed it stops developing since last year. Did the development of the program stop? Can I scan the latest  leaks on my websites using Vega?

**Comment by dma** [comment]
Thank you! It slowed because of our other projects, but I'll be doing maintenance when we can until we take it up again with more development effort (our team is small and focused)(.

**Comment by JerryLiao26** [comment]
Sorry for late reply. Thanks for all your hard work
