### ISSUE TITLE
compile source

### ISSUE THREAD

**Issue by mmghasemi** [subgraph/Vega#135]
hello 
i want to compile this source 
please help me to do it
i tested building veg in documents but it not work
can someone help me???

**Comment by prometx** [comment]
I am having issues with compilation as well:

Hmmmm, build failed :: http://paste.ubuntu.com/23473629/ :: seems like it's not handling the buildpack correctly?

Note: this is an armhf platform...

**Comment by robocoder** [comment]
Looks like it can't negotiate the cipher to use. support.subgraph.com doesn't support sslv3, while your jre doesn't seem to support the tls ciphers.

Perhaps download the buildpack manually and extract it?
