### ISSUE TITLE
Eclipse crash (OSX)

### ISSUE THREAD

**Issue by escrow001** [subgraph/Vega#139]
Hi,

I've an error message at launch

An error has occurred.
/Users/Users/.eclipse/152696853/configuration/1494188387908.log.

Thx

Mac OSX 10.12.4

**Comment by Arkanix** [comment]
LOG : 

!SESSION 2017-05-07 22:19:47.395 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.6.0_65
java.vendor=Apple Inc.
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=fr_FR
Framework arguments:  -keyring /Users/User/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/Arka/.eclipse_keyring -showlocation

!ENTRY org.eclipse.update.configurator 4 0 2017-05-07 22:19:49.699
!MESSAGE Could not install bundle plugins/com.google.guava_14.0.1.jar   Bundle "com.google.guava" version "14.0.1" has already been installed from: reference:file:plugins/com.google.guava_14.0.1.jar

**Comment by swarupsro** [comment]
how did you solved this ??

**Comment by haiderghaleb** [comment]
Move Vega app to your Application server and it will work without issues.

Running Vega directly from the virtual disk will cause an issue as you can not boot `.eclipse`.
