### ISSUE TITLE
Initialization Error: Could not open workspace

### ISSUE THREAD

**Issue by AlexDecarli** [subgraph/Vega#144]
Hi,

I´m using:

- Vega 1.0 - 64 bits
- Windows 10 enterprise x64 (up-to-date)
- Java 8, update 151 ( build 1.8.0_151-b12)
- Running as administrator (right click and execute as administrator)

on past, vega has working fine.
But, now, when I start, get the error: "Initialization Error: Could not open workspace"

Any idea ?
Thanks

**Comment by Web3DeveloperGuy** [comment]
I have resolved this by doing the following on windows 10 using vega 1.0 64bits

Visited:
C:\users\username
Deleted the .vega & .eclipse folders (show hidden files if you cant see them)

Uninstalled, reinstalled.

This clears all the workspace files, you could potentially do this another way by deleting some files or replacing with originals, but this definitely fixes your issue - you'll just need to re-run your reports.

**Comment by AlexDecarli** [comment]
Hi Mr Samdufeu,

It worked !!!!
Thanks a lot!
