### ISSUE TITLE
config

### ISSUE THREAD

**Issue by newdie484** [subgraph/Vega#153]
[1523124526039.log](https://github.com/subgraph/Vega/files/1886625/1523124526039.log)
](http://s8.picofile.com/file/8323119384/Selection_027.png)
how to fix that???

**Comment by ghost** [comment]
> http://s8.picofile.com/file/8323119384/Selection_027.png
> how to fix that???

The picture says : 
`less /home/redeye/infosec/vega/configuration/1523044276721.log`
please do not be lazy and follow the instructions!

**Comment by newdie484** [comment]
ok i send my log but i cant understand what is my problem

**Comment by newdie484** [comment]
http://s9.picofile.com/file/8323192592/Selection_031.png
this is complete my error

**Comment by newdie484** [comment]
http://www.panticz.de/Install-Vega-vulnerability-scanner-under-Ubuntu-Debian
i can fix my problem with this site
