### ISSUE TITLE
libwebkitgtk-1.0-0 no longer available

### ISSUE THREAD

**Issue by Austin-Src** [subgraph/Vega#177]
The fix for running Vega on Debian systems involves rolling back Java to version 8 and installing this dependency, but it is no longer available anywhere so Vega crashes irrecoverably on setup. Please see what can be done to fix this, thank you!

**Comment by Austin-Src** [comment]
I was able to find a mirror of the package, but it's insanely deprecated: 
http://mirrors.kernel.org/ubuntu/pool/universe/w/webkitgtk/libwebkitgtk-1.0-0_2.4.10-0ubuntu1_amd64.deb

**Comment by Kino1994** [comment]
Hi, here some fix:

Open terminal and write this:

1. sudo nano /etc/apt/sources.list
2. Add this entry to the file and save: 

> deb http://cz.archive.ubuntu.com/ubuntu bionic main universe

3. sudo apt-get update
4. sudo apt-get install libwebkitgtk-1.0-0 -> if you are using Vega and jdk of 64 bits
    sudo apt-get install libwebkitgtk-1.0-0:i386 -> if you are using Vega and jdk of 32 bits

5 Run Vega.

Ref: https://askubuntu.com/questions/1143637/how-do-i-install-libwebkitgtk-1-0-0-on-ubuntu-19-04

**Comment by Austin-Src** [comment]
Thank you, apologies for ineptitude with Linux packages.

**Comment by hkpanchani** [comment]
> Hi, here some fix:
> 
> Open terminal and write this:
> 
>     1. sudo nano /etc/apt/sources.list
> 
>     2. Add this entry to the file and save:
> 
> 
> > deb http://cz.archive.ubuntu.com/ubuntu bionic main universe
> 
>     1. sudo apt-get update
> 
>     2. sudo apt-get install libwebkitgtk-1.0-0 -> if you are using Vega and jdk of 64 bits
>        sudo apt-get install libwebkitgtk-1.0-0:i386 -> if you are using Vega and jdk of 32 bits
> 
> 
> 5 Run Vega.
> 
> Ref: https://askubuntu.com/questions/1143637/how-do-i-install-libwebkitgtk-1-0-0-on-ubuntu-19-04

I get the following error while installing via this method. Can anyone please help?

The following packages have unmet dependencies:
 libturbojpeg0 : Conflicts: libjpeg-turbo8 but 1.5.2-0ubuntu5 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

**Comment by pragmatic-github** [comment]
> Hi, here some fix:
> 
> Open terminal and write this:
> 
>     1. sudo nano /etc/apt/sources.list
> 
>     2. Add this entry to the file and save:
> 
> 
> > deb http://cz.archive.ubuntu.com/ubuntu bionic main universe
> 
>     3. sudo apt-get update
> 
>     4. sudo apt-get install libwebkitgtk-1.0-0 -> if you are using Vega and jdk of 64 bits
>        sudo apt-get install libwebkitgtk-1.0-0:i386 -> if you are using Vega and jdk of 32 bits
> 
> 
> 5 Run Vega.
> 
> Ref: https://askubuntu.com/questions/1143637/how-do-i-install-libwebkitgtk-1-0-0-on-ubuntu-19-04

Works for me.

**Comment by frodo763** [comment]
I followed these instructions and here is what was returned:

Err: 3 http://cz.archive.ubuntu.com/ubuntu bionic InRelease
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3B4FE6ACC0B21F32

E: The repository 'http://cz.archive.ubuntu.com/ubuntu bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

**Comment by cajda** [comment]
> I followed these instructions and here is what was returned:
> 
> Err: 3 http://cz.archive.ubuntu.com/ubuntu bionic InRelease The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3B4FE6ACC0B21F32
> 
> E: The repository 'http://cz.archive.ubuntu.com/ubuntu bionic InRelease' is not signed. N: Updating from such a repository can't be done securely, and is therefore disabled by default.

It can be solved via:
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32

This command adds proper public certificate to Ubuntu repository in you PC.

**Comment by ghost** [comment]
> > Hi, here some fix:
> > Open terminal and write this:
> > ```
> > 1. sudo nano /etc/apt/sources.list
> > 
> > 2. Add this entry to the file and save:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > deb http://cz.archive.ubuntu.com/ubuntu bionic main universe
> > 
> > 
> > ```
> > 1. sudo apt-get update
> > 
> > 2. sudo apt-get install libwebkitgtk-1.0-0 -> if you are using Vega and jdk of 64 bits
> >    sudo apt-get install libwebkitgtk-1.0-0:i386 -> if you are using Vega and jdk of 32 bits
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 5 Run Vega.
> > Ref: https://askubuntu.com/questions/1143637/how-do-i-install-libwebkitgtk-1-0-0-on-ubuntu-19-04
> 
> I get the following error while installing via this method. Can anyone please help?
> 
> The following packages have unmet dependencies: libturbojpeg0 : Conflicts: libjpeg-turbo8 but 1.5.2-0ubuntu5 is to be installed E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

Even I'm having the same error , package issues.

**Comment by Binoagustus** [comment]
> 

It was deprecated. is there any other way?

Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.MfnkbkySAm/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32
gpg: keyserver receive failed: No data

**Comment by roky005** [comment]
> > Hi, here some fix:
> > Open terminal and write this:
> > ```
> > 1. sudo nano /etc/apt/sources.list
> > 
> > 2. Add this entry to the file and save:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > deb http://cz.archive.ubuntu.com/ubuntu bionic main universe
> > 
> > 
> > ```
> > 1. sudo apt-get update
> > 
> > 2. sudo apt-get install libwebkitgtk-1.0-0 -> if you are using Vega and jdk of 64 bits
> >    sudo apt-get install libwebkitgtk-1.0-0:i386 -> if you are using Vega and jdk of 32 bits
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 5 Run Vega.
> > Ref: https://askubuntu.com/questions/1143637/how-do-i-install-libwebkitgtk-1-0-0-on-ubuntu-19-04
> 
> I get the following error while installing via this method. Can anyone please help?
> 
> The following packages have unmet dependencies: libturbojpeg0 : Conflicts: libjpeg-turbo8 but 1.5.2-0ubuntu5 is to be installed E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

same, if someone has the solution please reply

**Comment by Sudococommunity** [comment]
> > > Hi, here some fix:
> > > Open terminal and write this:
> > > ```
> > > 1. sudo nano /etc/apt/sources.list
> > > 
> > > 2. Add this entry to the file and save:
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > > deb http://cz.archive.ubuntu.com/ubuntu bionic main universe
> > > 
> > > 
> > > ```
> > > 1. sudo apt-get update
> > > 
> > > 2. sudo apt-get install libwebkitgtk-1.0-0 -> if you are using Vega and jdk of 64 bits
> > >    sudo apt-get install libwebkitgtk-1.0-0:i386 -> if you are using Vega and jdk of 32 bits
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 5 Run Vega.
> > > Ref: https://askubuntu.com/questions/1143637/how-do-i-install-libwebkitgtk-1-0-0-on-ubuntu-19-04
> > 
> > 
> > I get the following error while installing via this method. Can anyone please help?
> > The following packages have unmet dependencies: libturbojpeg0 : Conflicts: libjpeg-turbo8 but 1.5.2-0ubuntu5 is to be installed E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
> 
> same, if someone has the solution please reply

bro this will not work for debian probabaily you have install it from kali rolling or from debian
