### ISSUE TITLE
Create/Remove breakpoints - list not updating without refreshing window

### ISSUE THREAD

**Issue by robocoder** [subgraph/Vega#72]
Version: 1.0
Build id: devel-92
Mac OS X Lion 10.7.5 (11G63)
java version "1.6.0_51"
Java(TM) SE Runtime Environment (build 1.6.0_51-b11-457-11M4509)
Java HotSpot(TM) 64-Bit Server VM (build 20.51-b01-457, mixed mode)

Workaround is to click on the double-pause icon to refresh the interceptor options window.

**Comment by dma** [comment]
Thanks for pointing this out, yes, this is very annoying. I'll investigate it right away.

**Comment by dma** [comment]
This should be fixed in c119423c4aa36e5c0bbbf13ba0c5002b0aef9ab4 (build 96).
