### ISSUE TITLE
Wiki: Building Vega

### ISSUE THREAD

**Issue by robocoder** [subgraph/Vega#78]
https://github.com/subgraph/Vega/wiki/Building-Vega

Other than build_id, are there any other properties that devs might be interested in setting with ant?

**Comment by brl** [comment]
I can't think of anything in particular that somebody might want to do differently.  If you're interested in other things you can change, look at build/config/build.properties

We use PDE Build as a framework to build Vega, more information here: http://www.eclipse.org/pde/pde-build/

**Comment by robocoder** [comment]
Thanks for the reply.
