### ISSUE TITLE
Missing images from documentation

### ISSUE THREAD

**Issue by professor** [subgraph/Vega#87]
Just a heads up that there are many images missing from the documentation:
https://github.com/subgraph/Vega/wiki/Vega-Proxy

There's also a "Click here" that isn't linked. 

Perhaps this is a separate issue, but http://vega/ca.crt didn't generate the CA signing certificate. If it's also available on the file system, that would be handy too.

**Comment by dma** [comment]
Hi professor,

Yes, the broken images are a priority. I'll try to address that tonight. Thanks for the feedback.

As for the other issue, I can't reproduce it, I just got the certificate successfully with build 97 - what build/platform are you using? So forgive me if this is a dumb question, but are you sure your browser was configured to use the proxy, and that the proxy is turned on, before you attempted to access http://vega/ca.crt?

It is available on the filesystem once it is generated, but that only happens after you visit http://vega/ca.crt for the first time. It will be ~/.vega/ca.p12 (or the equivalent for your platform).

Thanks.

**Comment by dma** [comment]
Fixed. Thanks for letting us know. We're still missing system proxy config, as I don't have all of the screenshots (it varies by platform) -- we'll update this soon.
